# Generated by Django 4.0.4 on 2022-08-30 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergenceInformations',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('what_emergence', models.CharField(max_length=2000)),
                ('spending_cost', models.IntegerField()),
                ('spending_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'List of emergence',
            },
        ),
        migrations.CreateModel(
            name='EmployeeDetailInformations',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('employee_Full_name', models.CharField(max_length=200)),
                ('employee_gender', models.CharField(max_length=100)),
                ('employee_email_address', models.EmailField(max_length=254)),
                ('employee_start_date', models.DateField(auto_now_add=True)),
                ('employee_phone_number1', models.CharField(max_length=100)),
                ('employee_phone_number2', models.CharField(max_length=100)),
                ('employee_residence_area', models.CharField(max_length=100)),
                ('employee_username', models.CharField(blank=True, max_length=100, null=True)),
                ('employee_password', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'list of Employees',
            },
        ),
        migrations.CreateModel(
            name='ProductAndSupplierAndReceiverTable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('product_cost', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('product_quantity', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('total_product_cost', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('amount_to_sold', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'products received ',
            },
        ),
        migrations.CreateModel(
            name='ProductTable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('product_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'products List',
            },
        ),
        migrations.CreateModel(
            name='ShopsTable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('shop_name', models.CharField(max_length=100)),
                ('shop_street', models.CharField(max_length=100)),
                ('shop_district', models.CharField(max_length=100)),
                ('shop_region', models.CharField(max_length=100)),
                ('shop_start_date', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop_supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storeApp.employeedetailinformations')),
            ],
            options={
                'verbose_name_plural': 'Shops List',
            },
        ),
        migrations.CreateModel(
            name='productSoldInCash',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('number_of_product_nedeed', models.IntegerField()),
                ('date_product_sold', models.DateField()),
                ('total_product_cost', models.PositiveIntegerField(blank=True, null=True)),
                ('store_remain', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storeApp.productandsupplierandreceivertable')),
                ('shop_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storeApp.shopstable')),
                ('supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storeApp.employeedetailinformations')),
            ],
            options={
                'verbose_name_plural': 'products sold',
            },
        ),
        migrations.CreateModel(
            name='ProductAndSupplierTable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('supplier_full_name', models.CharField(max_length=100)),
                ('supplier_phone_number', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storeApp.producttable')),
            ],
            options={
                'verbose_name_plural': 'suppliers products List',
            },
        ),
        migrations.AddField(
            model_name='productandsupplierandreceivertable',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storeApp.producttable'),
        ),
        migrations.AddField(
            model_name='productandsupplierandreceivertable',
            name='product_receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storeApp.employeedetailinformations'),
        ),
        migrations.AddField(
            model_name='productandsupplierandreceivertable',
            name='shop_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storeApp.shopstable'),
        ),
        migrations.AddField(
            model_name='productandsupplierandreceivertable',
            name='supplier_full_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storeApp.productandsuppliertable'),
        ),
        migrations.CreateModel(
            name='CustomersOrders',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('customer_Full_name', models.CharField(max_length=2000)),
                ('customer_phone_number', models.IntegerField()),
                ('customer_order', models.CharField(max_length=2000)),
                ('customer_quantity_nedeed', models.IntegerField()),
                ('delivery_date_expected', models.DateField()),
                ('order_status', models.CharField(default='Pending', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'List of Orders from customers',
            },
        ),
        migrations.CreateModel(
            name='AuthorizeUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_dashboard', models.BooleanField(default=False)),
                ('manage_employees', models.BooleanField(default=False)),
                ('manage_shop', models.BooleanField(default=False)),
                ('manage_product', models.BooleanField(default=False)),
                ('manage_supplier', models.BooleanField(default=False)),
                ('manage_store', models.BooleanField(default=False)),
                ('manage_sales', models.BooleanField(default=True)),
                ('manage_orders', models.BooleanField(default=True)),
                ('manage_emergence', models.BooleanField(default=True)),
                ('help_center', models.BooleanField(default=True)),
                ('manage_authorizations', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('select_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Authorization',
            },
        ),
    ]
