# Generated by Django 4.0.4 on 2022-08-30 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopstable',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='shopstable',
            name='updated_at',
        ),
    ]
