# Generated by Django 4.0.4 on 2022-08-30 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeApp', '0002_remove_shopstable_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopstable',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
