# Generated by Django 4.0.4 on 2022-11-08 12:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeApp', '0016_alter_productsoldincash_date_product_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsoldincash',
            name='date_product_sold',
            field=models.DateTimeField(default=datetime.date(2022, 11, 8)),
        ),
    ]
