# Generated by Django 4.1.3 on 2022-11-09 08:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeApp', '0017_alter_productsoldincash_date_product_sold'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyStockOrAssets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(blank=True, max_length=100, null=True)),
                ('stock_number', models.CharField(blank=True, max_length=100, null=True)),
                ('stock_color', models.CharField(blank=True, max_length=100, null=True)),
                ('stock_size', models.CharField(blank=True, max_length=100, null=True)),
                ('stock_image', models.ImageField(upload_to='media')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Company Stock Or Assets',
            },
        ),
        migrations.AlterField(
            model_name='productsoldincash',
            name='date_product_sold',
            field=models.DateTimeField(default=datetime.date(2022, 11, 9)),
        ),
    ]
