# Generated by Django 4.1.3 on 2022-11-09 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeApp', '0018_companystockorassets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorizeusers',
            name='manage_company_stock_or_assets',
            field=models.BooleanField(default=True),
        ),
    ]
