
#_Civil_registration_numbers
'get_is_there_a_need_to_collect_civil_registration_numbers_on_the_deceased_id10069'

'get_do_you_have_a_death_certificate_from_the_civil_registry_id10069_a'

'get_death_registration_number_or_certificate_id10070'

'get_is_the_date_of_registration_available_id10071_check'

'get_date_of_registration_id10071'


'get_place_of_registration_id10072'

'get_national_identification_number_of_deceased_id10073'

# Community death
'get_did_the_baby_ever_cry_id10104'

'get_did_the_baby_cry_immediately_after_birth_even_if_only_a_little_bit_id10105'

'get_how_many_minutes_after_birth_did_the_baby_first_cry_id10106'

'get_did_the_baby_stop_being_able_to_cry_id10107'

'get_how_many_hours_before_death_did_the_baby_stop_crying_id10108'

'get_did_the_baby_ever_move_id10109'

'get_did_the_baby_ever_breathe_id101010'

'get_did_the_baby_breathe_immediately_after_birth_even_a_little_id101011'

'get_did_the_baby_have_a_breathing_problem_id101012'

'get_was_the_baby_given_assistance_to_breathe_at_birth_id101013'

'get_if_the_baby_did_not_show_any_sign_of_life_was_it_born_dead_id101014'

'get_were_there_any_bruises_or_signs_of_injury_on_babys_body_after_the_birth_id101015'

'get_was_the_babys_body_soft_pulpy_and_discoloured_and_the_skin_peeling_away_id101016'

# history of injuries_accidents
'get_did_she_or_he_suffer_from_any_injury_or_accident_that_led_to_her_his_death_id10077'

# injuries and accidents detail
'get_was_it_a_road_traffic_accident_id10079'

'get_what_was_her_his_role_in_the_road_traffic_accident_id10080'

'get_what_was_the_counterpart_that_was_hit_during_the_road_traffic_accident_id10081'

'get_was_she_or_he_injured_in_a_non_road_transport_accident_id10082'

'get_was_she_or_he_injured_in_a_fall_id10083'

'get_was_there_any_poisoning_id10084'

'get_did_she_or_he_die_of_drowning_id10085'

'get_was_she_or_injured_by_a_bite_or_sting_by_venomous_animal_id10086'

'get_was_she_or_he_injured_by_an_animal_or_insect_non_venomous_id10087'

'get_what_was_the_animal_insect_id10088'

'get_was_she_or_he_injured_by_burns_fire_id10089'

'get_was_she_or_he_subject_to_violence_suicide_homicide_abuse_id10090'

'get_was_she_or_he_injured_by_a_firearm_id10091'

'get_was_she_or_he_stabbed_cut_or_pierced_id10092'

'get_was_she_or_he_strangled_id10093'

'get_was_she_or_he_injured_by_a_blunt_force_id10094'

'get_was_she_or_he_injured_by_a_force_of_nature_id10095'

'get_was_it_electrocution_id10096'

'get_did_she_or_he_encounter_any_other_injury_id10097'

'get_was_the_injury_accidental_id10098'

'get_was_the_injury_self_inflicted_id10099'

'get_was_the_injury_intentionally_inflicted_by_someone_else_id100100' 

# health history
'get_how_many_days_old_was_the_baby_when_the_fatal_illness_started_id10351' 

'get_before_the_illness_that_led_to_death_was_the_baby_the_child_growing_normally_id10408' 

# duration of illness
'get_for_how_many_days_was_or_he_she_ill_before_death_id10120_0' 

'get_for_how_lon_was_she_or_he_ill_before_death_id10120_unit' 

'get_months_id10121' 

'get_years_id10122'

'get_days_id10120_1'

'get_calculated_number_of_days_with_illness_id10120' 


'get_did_she_or_he_die_suddenly_id10123' 



# Medical history associated with final illness
'get_was_there_any_diagnosis_by_a_health_professional_of_tuberculosis_id10125' 

'get_was_an_hiV_test_ever_positive_id10126' 

'get_was_there_any_diagnosis_by_a_health_professional_of_AidS_id10127' 


'get_did_she_or_he_have_a_recent_positive_test_by_a_health_professional_for_malaria_id10128' 

'get_did_she_or_he_have_a_recent_negative_test_by_a_health_professional_for_malaria_id10129' 

'get_was_there_any_diagnosis_by_a_health_professional_of_dengue_fever_ id10130'

'get_was_there_any_diagnosis_by_a_health_professional_of_measles_ id10131'

'get_was_there_any_diagnosis_by_a_health_professional_of_high_blood_pressure_ id10132'

'get_was_there_any_diagnosis_by_a_health_professional_of_heart_disease_id10133'


'get_was_there_any_diagnosis_by_a_health_professional_of_diabetes_id10134'

'get_was_there_any_diagnosis_by_a_health_professional_of_asthma_id10135'

'get_was_there_any_diagnosis_by_a_health_professional_of_epilepsy_id10136'


'get_was_there_any_diagnosis_by_a_health_professional_of_cancer_id10137'

'get_was_there_any_diagnosis_by_a_health_professional_of_Chronic_Obstructive_Pulmonary_Disease_COPD_id10138'


'get_was_there_any_diagnosis_by_a_health_professional_of_dementia_id10139'

'get_was_there_any_diagnosis_by_a_health_professional_of_depression_id10140'

'get_was_there_any_diagnosis_by_a_health_professional_of_stroke_id10141'


'get_was_there_any_diagnosis_by_a_health_professional_of_sickle_cell_disease_id10142'

'get_was_there_any_diagnosis_by_a_health_professional_of_kidney_disease_id10143'


'get_was_there_any_diagnosis_by_a_health_professional_of_liver_disease_id10144'


'get_was_there_any_diagnosis_by_a_health_professional_of_COViD_19_id10482'

'get_did_she_or_he_have_a_recent_test_by_a_health_professional_for_COViD_19_id10483'


'get_what_was_the_result_id10484'

# General signs and symptoms associated with final illness
'get_did_she_or_he_have_a_fever_id10147'

'get_how_many_days_did_the_fever_last_id10148_a'

'get_how_long_did_the_fever_last_id10148_units'

'get_enter_how_long_the_fever_lasted_in_days_id10148_b'

'get_enter_how_long_the_fever_lasted_in_months_id10148_c'

'get_how_many_days_did_the_fever_last_id10148'

'get_did_the_fever_continue_until_death_id10149'

'get_how_severe_was_the_fever_id10150'

'get_what_was_the_pattern_of_the_fever_id10151'

'get_did_she_or_he_have_night_sweats_id10152'

'get_did_she_or_he_have_a_cough_id10153'

'get_for_how__long_did_she_or_he_have_a_cough_id10154_units'

'get_enter_how_long_she_or_he_had_a_cough_in_days_id10154_a'

'get_enter_how_long_she_or_he_had_a_cough_in_months_id10154_b'

'get_for_how__many_days_did_she_or_he_have_a_cough_id10154'


'get_was_the_cough_productive_with_sputum_id10155'

'get_was_the_cough_very_severe_id10156'

'get_did_she_or_he_cough_up_blood_id10157'

'get_did_she_or_he_make_a_whooping_sound_when_coughing_id10158'

'get_did_she_or_he_have_any_difficulty_breathing_id10159'
 
# duration of breathing_difficulty
'get_for_how_many_days_did_the_difficulty_breathing_last_id10161_0'

'get_for_how_long_did_the_difficult_breathing_last_id10161_unit'

'get_enter_how_long_the_difficult_breathing_lasted_in_days_id10161_1'

'get_enter_how_long_the_difficult_breathing_lasted_in_months_id10162'

'get_enter_how_long_the_difficult_breathing_lasted_in_years_id10163'
'get_calculated_number_of_days_with_illness_id10161'


'get_was_the_difficulty_continuous_or_on_and_off_id10165'

'get_during_the_illness_that_led_to_death_did_she_or_he_have_fast_breathing_id10166'

'get_for_how_many_days_did_the_fast_breathing_last_id10167_a'

'get_how_long_did_the_fast_breathing_last_id10167_units'

'get_enter_how_long_the_fast_breathing_lasted_in_days_id10167_b'

'get_enter_how_long_the_fast_breathing_lasted_in_months_id10167_c'

'get_how_long_did_the_fast_breathing_last_id10167'

'get_did_she_or_he_have_breathlessness_id10168'

'get_for_how_many_days_did_she_or_he_have_breathlessness_id10169_a'

'get_how_long_did_she_or_he_have_breathlessness_id10169_units'
'get_enter_how_long_she_or_he_had_breathlessness_in_days_id10169_b'

'get_enter_how_long_she_or_he_had_breathlessness_in_months_id10169_c'

'get_how_long_did_she_or_he_have_breathlessness_id10169'

'get_was_she_or_he_unable_to_carry_out_daily_routines_due_to_breathlessness_id10170'


'get_was_she_or_he_breathless_while_lying_flat_id10171'

'get_did_you_see_the_lower_chest_wall_ribs_being_pulled_in_as_the_child_breathed_in_id10172'


'get_during_the_illness_that_led_to_death_did_his_her_breathing_sound_like_any_of_the_following_id10173_nc'

# (id10173_check)_it_is_not_possible_to_select_don't_know_or_refuse_together_with_other_options._Please_go_back_and_correct_the_selection._j/.//
'get_during_the_illness_that_led_to_death_did_she_or_he_have_wheezing_id10173_a'

'get_during_the_illness_that_led_to_death_did_his_her_breathing_sound_like_any_of_the_following_id10173'

'get_did_she_or_he_have_chest_pain_id10174'

'get_was_the_chest_pain_severe_id10175'
'get_how_many_days_before_death_did_she_or_he_have_chest_pain_id10176'

#_duration_of_the_chest_pain

'get_how_long_did_the_chest_pain_last__id10178_unit'

'get_enter_how_long_the_chest_pain_lasted_in_minutes_id10178'

'get_enter_how_long_the_chest_pain_lasted_in_hours_id10179'

'get_enter_how_long_the_chest_pain_lasted_in_days_id10179_1'

'get_did_she_or_he_have_more_frequent_loose_or_liquid_stools_than_usual_id10181'


'get_how_long_did_she_or_he_have_frequent_loose_or_liquid_stools_id10182_units'

'get_enter_how_long_she_or_he_had_frequent_loose_or_liquid_stools_in_days_id10182_a'


'get_enter_how_long_she_or_he_had_frequent_loose_or_liquid_stools_in_months_id10182_b'

'get_for_how_many_days_did_she_or_he_have_frequent_loose_or_liquid_stools_id10182'
'get_how_many_stools_did_the_baby_or_child_have_on_the_day_that_loose_liquid_stools_were_most_frequent_id10183'


'get_how_many_days_before_death_did_the_frequent_loose_or_liquid_stools_start_id10184_a'


'get_how_long_before_death_did_the_frequent_loose_or_liquid_stools_start_id10184_units'


'get_enter_how_long_before_death_the_frequent_loose_or_liquid_stools_started_in_days_id10184_b'

'get_enter_how_long_before_death_the_frequent_loose_or_liquid_stools_started_in_months_id10184_c'


'get_did_the_frequent_loose_or_liquid_stools_continue_until_death_id10185'

'get_at_any_time_during_the_final_illness_was_there_blood_in_the_stools_id10186'

'get_was_there_blood_in_the_stool_up_until_death_id10187'

'get_did_she_or_he_vomit_id10188'

'get_to_clarify_did_she_or_he_vomit_in_the_week_preceding_the_death_id10189'

'get_how_long_before_death_did_she_or_he_vomit_id10190_units'

'get_enter_how_long_before_deathshe_or_he_vomited_in_days_id10190_a'


'get_enter_how_long_before_deathshe_or_he_vomited_in_months_id10190_b'


'get_was_there_blood_in_the_vomit_id10191'


'get_was_the_vomit_black_id10192'

'get_did_she_or_he_have_any_belly_abdominal_problem_id10193'

'get_did_she_or_he_have_belly_abdominal_pain_id10194'

'get_was_the_belly_abdominal_pain_severe_id10195'

#_Belly_pain  
'get_for_how_long_did_she_or_he_have_belly_abdominal_pain__id10196_unit'


'get_enter_how_long_she_or_he_had__belly_abdominal_pain_in_hours_id10196'

'get_enter_how_long_she_or_he_had__belly_abdominal_pain_in_days_id10197_a'

'get_enter_how_long_she_or_he_had__belly_abdominal_pain_in_months_id10198'

'get_Calculated_number_of_days_with_belly_pain_id10197'
'get_was_the_pain_in_the_upper_or_lower_belly_abdomen_id10199'

'get_did_she_or_he_have_a_more_than_usually_protruding_belly_abdomen_id10200'

'get_for_how_long_before_death_did_she_or_he_have_a_more_than_usually_protruding_belly_abdomen_id10201_unit'

'get_enter_how_long_before_death_she_or_he_had_a_more_than_usually_protruding_belly_abdomen_in_days_id10201_a'

'get_enter_how_long_before_death_she_or_he_had_a_more_than_usually_protruding_belly_abdomen_in_months_id10202'

'get_Calculated_number_of_days_with_protruding_belly_abdomen_id10201'

'get_how_rapidly_did_she_or_he_develop_the_protruding_belly_abdomen_id10203'

'get_did_she_or_he_have_any_mass_in_the_belly_abdomen_id10204'

'get_for_how_long_did_she_or_he_have_a_mass_in_the_belly_abdomen_id10205_unit'

'get_enter_how_long_she_or_he_had_a_mass_in_the_belly_abdomen_in_days_id10205_a'

'get_enter_how_long_she_or_he_had_a_mass_in_the_belly_abdomen_in_months_id10206'

'get_Calculated_number_of_days_with_a_mass_in_the_belly_abdomen_id10205'

'get_did_she_or_he_have_a_severe_headache_id10207'


'get_did_she_or_he_have_a_stiff_neck_during_illness_that_led_to_death_id10208'


'get_how_long_before_death_did_she_or_he_have_stiff_neck_id10209_units'

'get_enter_how_long_before_death_did_she_or_he_have_stiff_neck_in_days_id10209_a'


'get_enter_how_long_before_death_did_she_or_he_have_stiff_neck_in_months_id10209_b'

'get_for_how_many_days_before_death_did_she_or_he_have_stiff_neck_id10209'

'get_did_she_or_he_have_a_painful_neck_during_the_illness_that_led_to_death_id10210'
 
'get_how_long_before_death_did_she_or_he_have_a_painful_neck_id10211_units'
 
'get_enter_how_long_before_death_she_or_he_had_a_painful_neck_in_days_id10211_a'
 
'get_enter_how_long_before_death_she_or_he_had_a_painful_neck_in_months_id10211_b'

'get_for_how_many_days_before_death_did_she_or_he_have_a_painful_neck_id10211'
 
'get_did_she_or_he_have_mental_confusion_id10212'
 
'get_how_long_did_she_or_he_have_mental_confusion_id10213_units'
 
'get_enter_how_long_she_or_he_had_mental_confusion_in_days_id10213_a'
 
'get_enter_how_long_she_or_he_had_mental_confusion_in_months_id10213_b'
 
'get_for_how_many_months_did_she_or_he_have_mental_confusion_id10213'

'get_was_she_or_he_unconscious_during_the_illness_thatledto_death_id10214'
 
'get_was_she_or_he_unconscious_for_more_than_24_hours_before_death_id10215'

'get_how_long_before_death_did_unconsciousness_start_id10216_units'

'get_enter_how_long_before_death_unconsciousness_started_in_hours_id10216_a'

'get_enter_how_long_before_death_unconsciousness_started_in_days_id10216_b'
 
'get_how_many_hours_before_death_did_unconsciousness_start_id10216'
 
'get_did_the_unconsciousness_start_suddenly_quickly_at_least_within_a_single_day_id10217'
 
'get_did_the_unconsciousness_continue_until_death_id10218'
 
'get_did_she_or_he_have_convulsions_id10219'

'get_did_she_or_he_experience_any_generalized_convulsions_or_fits_during_the_illness_that_led_to_death_id10220'
 
'get_for_how_many_minutes_did_the_convulsions_last_id10221'
 
'get_did_she_or_he_become_unconscious_immediately_after_the_convulsion_id10222'
 
'get_did_she_or_he_have_any_urine_problems_id10223'
 
'get_did_she_or_he_go_to_urinate_more_often_than_usual_id10225'
 
'get_during_the_final_illness_did_she_or_he_ever_pass_blood_in_the_urine_id10226'
 
'get_did_she_or_he_stop_urinating_id10224'
 
'get_did_she_or_he_have_sores_or_ulcers_anywhere_on_the_body_id10227'

'get_did_she_or_he_have_sores_id10228'

'get_did_the_sores_have_clear_fluid_or_pus_id10229'
 
'get_did_she_or_he_have_an_ulcer_pit_on_the_foot_id10230'
 
 
'get_did_the_ulcer_on_the_foot_ooze_pus_id10231'
 
'get_how_long__did_the_ulcer_on_the_foot_ooze_pus_id10232_units'
 
'get_enter_how_long_the_ulcer_on_the_foot_oozed_pus_in_days_id10232_a'
 
'get_enter_how_long_the_ulcer_on_the_foot_oozed_pus_in_months_id10232_b'
 
'get_for_how_many_days_did_the_ulcer_on_the_foot_ooze_pus_id10232'
 
'get_during_the_illness_that_led_to_death_did_she_or_he_have_any_skin_rash_id10233'
 

'get_for_how_many_days_did_she_or_he_have_the_skin_rash_id10234'
 
'get_where_was_the_rash_id10235'
 

# (id10235_check)_it_is_not_possible_to_select_doesn't_Know_or_Refused_to_answer_together_with_other_options._Please_go_back_and_correct_the_selection._
'get_did_she_or_he_have_measles_rash_use_local_term_id10236'
 
'get_did_she_or_he_ever_have_shingles_or_herpes_zoster_id10237'
 
'get_during_the_illness_that_led_to_death_did_her_his_skin_flake_off_in_patches_id10238'
 
'get_during_the_illness_that_led_to_death_did_he_she_have_areas_of_the_skin_that_turned_black_id10239'
 
'get_during_the_illness_that_led_to_death_did_he_she_have_areas_of_the_skin_with_redness_and_swelling_id10240'
 
'get_during_the_illness_that_led_to_death_did_she_or_he_bleed_from_anywhere_id10241'
 
'get_did_she_or_he_bleed_from_the_nose_mouth_or_anus_id10242'
 
'get_did_she_or_he_have_noticeable_weight_loss_id10243'
 
'get_was_she_or_he_severely_thin_or_wasted_id10244'
 
'get_during_the_illness_that_led_to_death_did_s_he_have_a_whitish_rash_inside_the_mouth_or_on_the_tongue_id10245'

'get_did_she_or_he_have_stiffness_of_the_whole_body_or_was_unable_to_open_the_mouth_id10246'
'get_did_she_or_he_have_puffiness_of_the_face_id10247'
 
'get_how_long_did_she_or_he_have_puffiness_of_the_face_id10248_units'
 
'get_enter_how_long_she_or_he_had_puffiness_of_the_face_in_days_id10248_a'
 
'get_enter_how_long_she_or_he_had_puffiness_of_the_face_in_months_id10248_b'
 
'get_for_how_many_days_did_she_or_he_have_puffiness_of_the_face_id10248'
 
'get_during_the_illness_that_led_to_death_did_she_or_he_have_swollen_legs_or_feet_id10249'
'get_how_long_did_the_swelling_last_id10250_units'
'get_enter_how_long_the_swelling_lasted_in_days_id10250_a'
'get_how_many_days_did_the_swelling_last_id10250_b'
'get_did_she_or_he_have_both_feet_swollen_id10251'
'get_did_she_or_he_have_general_puffiness_all_over_his_her_body_id10252'
'get_did_she_or_he_have_any_lumps_id10253'
'get_did_she_or_he_have_any_lumps_or_lesions_in_the_mouth_id10254'
'get_did_she_or_he_have_any_lumps_on_the_neck_id10255'
'get_did_she_or_he_have_any_lumps_on_the_armpit_id10256'
'get_did_she_or_he_have_any_lumps_on_the_groin_id10257'
'get_was_she_or_he_in_any_way_paralysed_id10258'
'get_did_she_or_he_have_paralysis_of_only_one_side_of_the_body_id10259'
'get_which_were_the_limbs_or_body_parts_paralysed_id10260'
# (id10260_check)_it_is_not_possible_to_select_only_one_side_paralysed_and_left_and_right_side_or__whole_body_together._Please_go_back_and_correct_the_selection._
# (id10260_check2)_it_is not possible to select doesn't Know or Refused_to_answer_together_with_other_options._Please_go_back_and_correct_the_selection._
'get_did_she_or_he_have_difficulty_swallowing_id10261'
 
'get_for_how_long_before_death_did_she_or_he_have_difficulty_swallowing_id10262_units'

'get_enter_how_long_before_death_she_or_he_had_difficulty_swallowing_in_days_id10262_a'

'get_enter_how_long_before_death_she_or_he_had_difficulty_swallowing_in_months_id10262_b'

'get_for_how_many_days_before_death_did_she_or_he_have_difficulty_swallowing_id10262'

'get_was_the_difficulty_with_swallowing_with_solids_liquids_or_both_id10263'

'get_did_she_or_he_have_pain_upon_swallowing_id10264'

'get_did_she_or_he_have_yellow_discoloration_of_the_eyes_id10265'

'get_for_how_long_did_she_or_he_have_the_yellow_discoloration_id10266_units'

'get_enter_how_long_she_or_he_had_the_yellow_discoloration_in_days_id10266_a'


 
'get_enter_how_long_she_or_he_had_the_yellow_discoloration_in_months_id10266_b'

'get_for_how_many_days_did_she_or_he_have_the_yellow_discoloration_id10266'

'get_did_her_his_hair_change_in_color_to_a_reddish_or_yellowish_color_id10267'

'get_did_she_or_he_look_pale_thinning_lack_of_blood_or_have_pale_palms_eyes_or_nail_beds_id10268'


 
'get_did_she_or_he_have_sunken_eyes_id10269'

 
'get_did_she_or_he_drink_a_lot_more_water_than_usual_id10270'

 
'get_was_the_baby_able_to_suckle_or_bottle_feed_within_the_first_24_hours_after_birth_id10271'

 
'get_did_the_baby_ever_suckle_in_a_normal_way_id10272'

'get_did_the_baby_stop_suckling_id10273'

'get_how_many_days_after_birth_did_the_baby_stop_suckling_id10274_a'

'get_how_long_after_birth_did_the_baby_stop_suckling_id10274_units'

'get_enter_how_long_after_birth__the_baby_stopped_suckling_in_days_id10274_b'

'get_enter_how_long_after_birth__the_baby_stopped_suckling_in_months_id10274_c'

'get_how_many_days_after_birth_did_the_baby_stop_suckling_id10274'

'get_did_the_baby_have_convulsions_starting_within_the_first_24_hours_of_life_id10275'

'get_did_the_baby_have_convulsions_starting_more_than_24_hours_after_birth_id10276'

'get_did_the_babys_body_become_stiff_with_the_back_arched_backwards_id10277'

 
'get_during_the_illness_that_led_to_death_did_the_baby_have_a_bulging_or_raised_fontanelle__id10278'

'get_during_the_illness_that_led_to_death_did_the_baby_have_a_sunken_fontanelle_id10279'

'get_during_the_illness_that_led_to_death_did_the_baby_become_unresponsive_or_unconscious_id10281'

'get_did_the_baby_become_unresponsive_or_unconscious_soon_after_birth_within_less_than_24_hours_id10282'
 
#_Neonatal_child_questions_part_C
'get_during_the_illness_that_led_to_death_did_the_baby_become_cold_to_touch_id10284'

'get_how_many_days_old_was_the_baby_when_it_started_feeling_cold_to_touch_id10285'

'get_during_the_illness_that_led_to_death_did_the_baby_become_lethargic_after_a_period_of_normal_activity_id10286'

'get_did_the_baby_have_redness_or_pus_drainage_from_the_umbilical_cord_stump_id10287'


'get_during_the_illness_that_led_to_death_did_the_baby_have_skin_ulcers_or_pits_id10288'

'get_during_the_illness_that_led_to_death_did_the_baby_have_yellow_skin_palms_hand_or_soles_foot_id10289'

'get_did_the_baby_or_infant_appear_to_be_healthy_and_then_just_die_suddenly_id10290'



# pregnancy_women	Signs and symptoms associated with pregnancy and women
'get_did_she_have_any_swelling_or_lump_in_the_breast_Id10294'

'get_did_she_have_any_ulcers_pits_in_the_breast_Id10295'

'get_did_she_ever_have_a_period_or_menstruate_Id10296'

'get_when_she_had_her_period_did_she_have_vaginal_bleeding_in_between_menstrual_periods_Id10297'

'get_was_the_bleeding_excessive_Id10298'

'get_was_there_excessive_vaginal_bleeding_in_the_week_prior_to_death_Id10301'

'get_did_her_menstrual_period_stop_naturally_because_of_menopause_or_removal_of_uterus_Id10299'

'get_at_the_time_of_death_was_her_period_overdue_Id10302'

'get_for_how_many_weeks_had_her_period_been_overdue_Id10303'

'get_did_she_have_vaginal_bleeding_after_cessation_of_menstruation_Id10300'

'get_did_she_have_a_sharp_pain_in_her_belly_abdomen_shortly_before_death_Id10304'

'get_was_she_pregnant_or_in_labour_at_the_time_of_death_Id10305'

'get_did_she_die_within_6_weeks_of_delivery_abortion_or_miscarriage_Id10306'

'get_did_this_woman_die_more_than_6_weeks_after_being_pregnant_or_delivering_a_baby_Id10307'

'get_was_this_a_woman_who_died_less_than_1_year_after_being_pregnant_or_delivering_a_baby_Id10308'

'get_for_how_many_months_was_she_pregnant_Id10309'

'get_please_confirm_when_she_died_she_was_NEITHER_pregnant_NOR_had_delivered_had_an_abortion_or_miscarried_within_12_months_of_when_she_died_is_that_right_Id10310'

# Id10310_check	(Id10310_check) if_the_response_is_NO_DONT_KNOw_OR_REFUSED_it_indicates_some_uncertainty_as_to_whether_the_cause_of_death_could_have_been_a_maternal_or_pregnancy_related_cause_Go_back_to_the_question_did_she_ever_have_a_period_or_menstruate_and_follow_the_process_again_If_it_is_confirmed_that_the_death_was_related_to_pregnancy_proceed_with_the_next_question_did_she_die_during_labour_or_delivery_
#_group_maternal	Questions_about_possible_maternal_deaths
'get_did_she_die_during_labour_or_delivery_Id10312'

'get_did_she_die_after_delivering_a_baby_Id10313'

'get_did_she_die_within_24_hours_after_delivery_Id10314'

'get_did_she_die_within_6_weeks_of_childbirth_Id10315_a'

'get_did_she_die_within_6_weeks_of_childbirth_Id10315'

'get_did_she_give_birth_to_a_live_baby_within_6_weeks_of_her_death_Id10316'

'get_get_did_she_die_during_or_after_a_multiple_pregnancy_Id10317'

'get_was_she_breastfeeding_the_child_in_the_days_before_death_Id10318'

'get_how_many_births_including_still_births_did_she_the_mother_have_before_this_baby_Id10319'

'get_had_she_had_any_previous_Caesarean_section_Id10320'

'get_during_pregnancy_did_she_suffer_from_high_blood_pressure_Id10321'

'get_did_she_have_foul_smelling_vaginal_discharge_during_pregnancy_or_after_delivery_Id10322'

'get_during_the_last_3_months_of_pregnancy_did_she_suffer_from_convulsions_Id10323'

'get_during_the_last_3_months_of_pregnancy_did_she_suffer_from_blurred_vision_Id10324'

'get_did_bleeding_occur_while_she_was_pregnant_Id10325'

'get_was_there_vaginal_bleeding_during_the_first_6_months_of_pregnancy_Id10326'

'get_was_there_vaginal_bleeding_during_the_last_3_months_of_pregnancy_but_before_labour_started_Id10327'


'get_did_she_have_excessive_bleeding_during_labour_or_delivery_Id10328'

'get_did_she_have_excessive_bleeding_after_delivery_or_abortion_Id10329'

'get_was_the_placenta_completely_delivered_Id10330'

'get_did_she_deliver_or_try_to_deliver_an_abnormally_positioned_baby_Id10331'

'get_for_how_many_hours_was_she_in_labour_Id10332'

'get_did_she_attempt_to_terminate_the_pregnancy_Id10333'

'get_did_she_recently_have_a_pregnancy_that_ended_in_an_abortion_spontaneous_or_induced_Id10334'

'get_get_did_she_die_during_an_abortion_Id10335'

'get_get_did_she_die_within_6_weeks_of_having_an_abortion_Id10336'

'get_where_did_she_give_birth_complete_the_miscarriage_have_the_abortion_Id10337'

'get_did_she_receive_professional_assistance_during_the_delivery_Id10338'

'get_who_delivered_the_baby_completed_the_miscarriage___performed_the_abortion_Id10339'
 
#_deliverytype	how_did_the_mother_deliver_her_baby
'get_was_the_delivery_normal_vaginal_without_forceps_or_vacuum_Id10342'
 
'get_was_the_delivery_vaginal_with_forceps_or_vacuum_Id10343'
 
'get_was_the_delivery_a_Caesarean_section_Id10344'
 
'get_was_the_baby_born_more_than_one_month_early_Id10347'
 
	
'get_did_she_have_an_operation_to_remove_her_uterus_shortly_before_death_Id10340'
 
	
#_neonatal_child	Neonatal_and_child_history_signs_and_symptoms
'get_how_old_was_the_child_when_the_fatal_illness_started_Id10352_units'
 
	
'get_Enter_how_old_the_child_was__when_the_fatal_illness_started_in_months_Id10352_a'
 
	
'get_Enter_how_old_the_child_was__when_the_fatal_illness_started_in_years_Id10352_b'
 
	
'get_how_many_years_old_was_the_child_when_the_fatal_illness_started_Id10352'

#_neonatal_childA	Neonatal_child_questions_part_A
	
'get_was_the_child_part_of_a_multiple__birth_Id10354'

 
'get_was_the_child_the_first_second_or_later_in_the_birth_order_Id10355'

'get_is_the_mother_still_alive_Id10356'

'get_did_the_mother_die_before_during_or_after_the_delivery_Id10357'


#_moth_death	Time_between_delivery_and_death_of_mother

'get_how_long_after_the_delivery_did_the_mother_die_Id10358_units'

'get_how_many_months_after_the_delivery_did_the_mother_die_Id10358'

'get_how_many_days_after_the_delivery_did_the_mother_die_Id10359'

'get_how_many_weeks_after_the_delivery_did_the_mother_die_Id10359_a'

	
'get_where_was_the_deceased_born_Id10360'

	
'get_did_you_the_mother_receive_professional_assistance_during_the_delivery_Id10361'


	
'get_at_birth_was_the_baby_of_usual_size_Id10362'

	
'get_at_birth_was_the_baby_smaller_than_usual_weighing_under_2point5_kg_Id10363'

	
'get_at_birth_was_the_baby_smaller_than_usual_weighing_under_2point5_kg_Id10363'

	
'get_at_birth_was_the_baby_very_much_smaller_than_usual_weighing_under_1_kg_Id10364'

	
'get_at_birth_was_the_baby_larger_than_usual_weighing_over_4point5_kg_Id10365'

#_id1036X_check	(id1036X_check)_it_is_not_possible_to_select_"No_usual_size_at_Birth"_"No_weighing_under_2.5_kg"_and_"No_weighing_over_4.5_kg"_together._Please_go_back_and_correct_the_selection._
	
'get_what_was_the_weight_in_grammes_of_the_deceased_at_birth_Id10366'
	
'get_how_many_months_long_was_the_pregnancy_before_the_child_was_born_Id10367'

'get_were_there_any_complications_in_the_late_part_of_the_pregnancy_defined_as_the_last_3_months_before_labour_Id10368'

'get_were_there_any_complications_during_labour_or_delivery_Id10369'

'get_was_any_part_of_the_baby_physically_abnormal_at_time_of_delivery_for_example_body_part_too_large_or_too_small_additional_growth_on_body_Id10370'

'get_did_the_baby_child_have_a_swelling_or_defect_on_the_back_at_time_of_birth_Id10371'

'get_did_the_baby_child_have_a_very_large_head_at_time_of_birth_Id10372'

'get_did_the_baby_child_have_a_very_small_head_at_time_of_birth_Id10373'

'get_how_many_births_including_stillbirths_did_the_babys_mother_have_before_this_baby_Id10394'

#_neonatal_childB	(neonatal_childB)_Neonatal_child_questions_part_B

'get_was_the_baby_moving_in_the_last_few_days_before_the_birth_Id10376'

'get_did_the_baby_stop_moving_in_the_womb_before_labour_started_Id10377'
 
#_babmove	Baby_moving
'get_how_long_before_labour_did_you_the_mother_last_feel_the_baby_move_Id10379_unit'
 
'get_Enter_how_long_before_labour_did_you_the_mother_last_feel_the_baby_move_in_days_Id10379'
 
'get_Enter_how_long_before_labour_did_you_the_mother_last_feel_the_baby_move_in_hours_Id10380'
 
	
'get_how_many_hours_did_labour_and_delivery_take_Id10382'
 
	
'get_was_the_baby_born_24_hours_or_more_after_the_water_broke_Id10383'
 
	
'get_what_was_the_colour_of_the_liquor_when_the_water_broke_Id10385'
 
#_mother_deliv	(mother_deliv)_how_was_the_baby_delivered
'get_was_the_delivery_normal_vaginal_without_forceps_or_vacuum_Id10387'

'get_was_the_delivery_vaginal_with_forceps_or_vacuum_Id10388'

'get_was_the_delivery_a_Caesarean_section_Id10389'

'get_was_the_delivery_a_Caesarean_section_Id10389'

# id10389_check	(id10389_check) it_is_not_possible_to_select_No_to_all_three_previous_questions._Please_go_back_and_review_the_answers._
'get_did_you_the_mother_receive_any_vaccinations_since_reaching_adulthood_including_during_this_pregnancy_Id10391' 
'get_how_many_doses_Id10392' 
'get_did_you_the_mother_receive_tetanus_toxoid_TT_vaccine_Id10393' 
'get_during_labour_did_the_babys_mother_suffer_from_fever_Id10395' 
'get_during_the_last_3_months_of_pregnancy_labour_or_delivery_did_you_the_babys_mother_suffer_from_high_blood_pressure_Id10396' 
'get_did_you_the_babys_mother_have_diabetes_mellitus_Id10397' 
'get_did_you_the_babys_mother_have_foul_smelling_vaginal_discharge_during_pregnancy_or_after_delivery_Id10398' 
 
'get_during_the_last_3_months_of_pregnancy_labour_or_delivery_did_you_the_babys_mother_suffer_from_convulsions_Id10399' 
 
'get_during_the_last_3_months_of_pregnancy_did_you_the_babys_mother_suffer_from_blurred_vision_Id10400'
 
'get_did_you_the_babys_mother_have_severe_anemia_Id10401'

'get_did_you_the_babys_mother_have_vaginal_bleeding_during_the_last_3_months_of_pregnancy_but_before_labour_started_Id10402'


'get_did_the_babys_bottom_feet_arm_or_hand_come_out_of_the_vagina_before_its_head_Id10403'


'get_was_the_umbilical_cord_wrapped_more_than_once_around_the_neck_of_the_child_at_birth_Id10404'


'get_was_the_umbilical_cord_delivered_first_Id10405'

'get_was_the_baby_blue_in_colour_at_birth_Id10406'

#_risk_factors	Risk_factors

'get_did_she_or_he__drink_alcohol_Id10411'

'get_did_she_or_he__use_tobacco_Id10412'

'get_did_she_or_he__smoke_tobacco_cigarette_cigar_pipe_etc_Id10413'

'what_kind_of_tobacco_get_did_she_or_he__use_Id10414'

# id10414_check	(id10414_check)_it_is_not_possible_to_select_cigarettes_or_pipe_and_"no"_to_"get_did_she_or_he__smoke_tobacco"._Please_go_back_and_correct_the_selections.
'get_how_many_cigarettes_get_did_she_or_he__smoke_daily_Id10415'

 
'get_how_many_times_didshe_or_he__use_tobacco_products_each_day_Id10416'
	
#_health_service_utilization	Health_service_utilisation
'get_did_she_or_he__receive_any_treatment_for_the_illness_that_led_to_death_Id10418'
	
'get_did_she_or_he_receive_oral_rehydration_salts_Id10419'
	
'get_did_she_or_he_receive_or_need_intravenous_fluids_drip_treatment_Id10420'
	
'get_did_she_or_he_receive_or_need_a_blood_transfusion_Id10421'
	
'get_did_she_or_he_receive_or_need_treatment_food_through_a_tube_passed_through_the_nose_Id10422'
	

'get_did_she_or_he_receive_or_need_injectable_antibiotics_Id10423'
	
'get_did_she_or_he_receive_or_need_antiretroviral_therapy_ART_Id10424'
	
'get_did_she_or_he_have_or_need_an_operation_for_the_illness_Id10425'
	

'get_did_she_or_he_have_the_operation_within_1_month_before_death_Id10426'
	

'get_was_she_or_he__discharged_from_hospital_very_ill_Id10427'
	
'get_did_she_or_he__receive_any_immunizations_Id10428'
	
'get_do_you_have_the_childs_vaccination_card_Id10429'
	
'get_can_i_see_the_vaccination_card_note_the_vaccines_the_child_received_Id10430'
	
'get_select_EPI_vaccines_done_Id10431'
	
# id10431_check	(id10431_check)_it_is_not_possible_to_select_"No_vaccines"_"don't_know"_or_"refuse"_together_with_other_options._Please_go_back_and_correct_the_selection._

'get_was_care_sought_outside_the_home_while_she_or_he__had_this_illness_Id10432'
	
'get_where_or_from_whom_did_you_seek_care_Id10433'

# id10433_check	(id10433_check)_it_is_not_possible_to_select_"don't_know"_or_"refuse"_together_with_other_options._Please_go_back_and_correct_the_selection._
	
'get_what_was_the_name_and_address_of_any_hospital_health_center_or_clinic_where_care_was_sought_Id10434'

'get_did_a_health_care_worker_tell_you_the_cause_of_death_Id10435'

'get_what_did_the_health_care_worker_say_Id10436'

'get_do_you_have_any_health_records_that_belonged_to_the_deceased_Id10437'

'get_can_i_see_the_health_records_Id10438'


# Id10439_check	(Id10439_check)_is_the_date_of_the_most_recent_(last)_visit_available
'get_record_the_date_of_the_most_recent_last_visit_Id10439'

# Id10440_check	(Id10440_check)_is_the_date_of_the_second_most_recent_visit_available
'get_record_the_date_of_the_second_most_recent_visit_Id10440'

# Id10441_check	(Id10441_check)_is_the_date_of_the_last_note_on_the_health_records_available
'get_record_the_date_of_the_last_note_on_the_health_records_Id10441'

'get_record_the_weight_in_kilogrammes_written_at_the_most_recent_last_visit_Id10442'

'get_record_the_weight_in_kilogrammes_written_at_the_second_most_recent_visit_Id10443'


'get_transcribe_the_last_note_on_the_health_records_Id10444'

'get_has_the_deceaseds_biological_mother_ever_been_tested_for_HIV_Id10445'

'get_has_the_deceaseds_biological_mother_ever_been_told_she_had_HIV_AIDS_by_a_health_worker_Id10446'

#_back_context	Background_and_context
'get_in_the_final_days_before_death_did_s_he_travel_to_a_hospital_or_health_facility_Id10450'

'get_get_did_she_or_he__use_motorised_transport_to_get_to_the_hospital_or_health_facility_Id10451'

'get_were_there_any_problems_during_admission_to_the_hospital_or_health_facility_Id10452'


'get_were_there_any_problems_with_the_way_she_or_he__was_treated_medical_treatment_procedures_interpersonal_attitudes_respect_dignity_in_the_hospital_or_health_facility_Id10453'

'get_were_there_any_problems_getting_medications_or_diagnostic_tests_in_the_hospital_or_health_facility_Id10454'

'get_does_it_take_more_than_2_hours_to_get_to_the_nearest_hospital_or_health_facility_from_the_deceaseds_household_Id10455'

'get_in_the_final_days_before_death_were_there_any_doubts_about_whether_medical_care_was_needed_Id10456'

'get_in_the_final_days_before_death_was_traditional_medicine_used_Id10457'

'get_in_the_final_days_before_death_did_anyone_use_a_telephone_or_cell_phone_to_call_for_help_Id10458'

'get_over_the_course_of_illness_did_the_total_costs_of_care_and_treatment_prohibit_other_household_payments_Id10459'


#_Health_ins	Health_insuarance
'get_did_the_deceased_have_Health_insuarance_TZ001'

'get_which_among_the_following_Health_insuarances_did_the_deceased_have_TZ002'

'get_Other_Specify_TZ002_other'

'get_did_the_deceased_use_his_her_Health_insuarance_during_his_her_final_illness_TZ003'


	
'get_which_services_did_the_Health_insuarance_provide_TZ004'

'get_Other_Specify_TZ004_other'

'get_why_did_the_deceased_not_use_his_her_health_insuarance_TZ005'

'get_there_was_another_problem_with_using_the_insuarance_specify_TZ005_a'


#_deathcert	Death_certificate_with_cause_of_death
'get_was_a_medical_certificate_of_cause_of_death_issued_Id10462'

'get_can_I_see_the_medical_certificate_of_cause_of_death_Id10463'

'get_record_the_immediate_cause_of_death_from_the_certificate_line_1a_Id10464'

'get_duration_Ia_Id10465'

'get_record_the_first_antecedent_cause_of_death_from_the_certificate__line_1b_Id10466'

'get_duration_Ib_Id10467'

'get_record_the_second_antecedent_cause_of_death_from_the_certificate_line_1c_Id10468'


'get_duration_Ic_Id10469'

'get_record_the_third_antecedent_cause_of_death_from_the_certificate_line_1d_Id10470'

'get_duration_Id_Id10471'


'get_record_the_contributing_causes_of_death_from_the_certificate_part_2_Id10472'

'get_duration_part2_Id10473'

#_narrat	Open_narrative
'get_Thank_you_for_your_information_Now_can_you_please_tell_me_in_your_own_words_about_the_events_that_led_to_the_death_Id10476'

'get_select_any_of_the_following_words_that_were_mentioned_as_present_in_the_narrative_Id10477'

'get_select_any_of_the_following_words_that_were_mentioned_as_present_in_the_narrative_Id10478'

'get_select_any_of_the_following_words_that_were_mentioned_as_present_in_the_narrative_Id10479'


# id10477_check	(id10477_check)_it_is_not_possible_to_select_"don't_know"_or_"None_of_the_above"_together_with_other_options._Please_go_back_and_correct_the_selection._
# id10478_check	(id10478_check)_it_is_not_possible_to_select_"don't_know"_or_"None_of_the_above"_together_with_other_options._Please_go_back_and_correct_the_selection._
# id10479_check	(id10479_check)_it_is_not_possible_to_select_"don't_know"_or_"None_of_the_above"_together_with_other_options._Please_go_back_and_correct_the_selection._
'get_End_time_of_the_interview_Id10481'
	
#_comment	(comment)_Comment
'get_Collect_the_GPS_coordinates_of_this_location_gps_location'
	
'get_the_GPS_coordinates_represents_gps_details'

